name: basic demo

on: [push]

jobs:
  # u can have one jobs with many steps or multiple jobs with steps each
  demo:
    runs-on: macos-12
    steps:
      - name: a basic echo
        run: echo Hello!
  demo2:
    runs-on: ubuntu-latest
    steps:
      - name: a demo2 echo
        run: echo Hello from demo2!
